### ISSUE TITLE
Brace expansion

### ISSUE THREAD

**Issue by kashav** [kshvmdn/scaffold#1]
For some reason, brace expansion isn't working with [`exec.Command`](https://golang.org/pkg/os/exec/#Command). Right now, I'm just [printing the `mkdir` and `touch` commands](https://github.com/kshvmdn/scaffold/blob/master/scaffold.go#L116:L121), so they can still be copied/pasted and run, but it'd be definitely huge to get this working so we can just build the full directory without having to run any extra commands manually.

What's happening is that the script is interpreting the brackets as strings, so it's creating directories with braces in the names, rather than using the braces to determine structure.

**Comment by mholt** [comment]
> For some reason, brace expansion isn't working with exec.Command

I'm pretty sure exec.Command doesn't do any interpretation of the arguments; you'll have to do the expansion manually.

**Comment by kashav** [comment]
@mholt Hey - thanks for the tip! I wonder if the following would work then 🤔 -- 

```go
exec.Command("mkdir", "-p", "foo/", "{", "bar", ",", "baz", "}")
```

Anyways, ended up building a list of all paths and using os.MkdirAll / os.Create to do this (https://github.com/kshvmdn/scaffold/commit/b0967e92aca11a8d6ca96c3d470c65c5167569cd) - thanks again!

Edit: never mind, that doesn't work, I really don't know why I thought it would. 😅
